### PR TITLE
Update AppVeyor configuration.

### LINKED ISSUE #5: Compiling in Windows (AppVeyor)
[google/brotli](https://github.com/google/brotli) seems to compile under Windows as it has an AppVeyor [setup in the repo](https://github.com/google/brotli/search?utf8=%E2%9C%93&q=appveyor).

Can iltorb build under Windows?
I'm trying to integrate it into `grunt-contrib-compress` and currently the [build fails](https://ci.appveyor.com/project/radkodinev/grunt-contrib-compress/build/4).
Any guidelines or help would be highly appreciated. Thanks!

Note: I'm not a Windows user, not a C/C++ developer, and don't have experience with AppVeyor, unfortunately.

### PR DESCRIPTION
**Pull request by XhmikosR**
* Test node.js v0.10 - v5
* Use MSVC 2015

Fixes #5.

It still needs some tweaking/cleaning up.

@FeodorFitsner: Any idea how I can do this (or why it fails)?

```yml
install:
  - cmd: >-
      IF %nodejs_version% == "0.10" (
        npm install -g npm@3
        SET PATH=%APPDATA%\npm;%PATH%
      )
      IF %PLATFORM% == "x64" (
        CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
      ) ELSE (
        CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86
      )
```

### CODE REVIEW

**Comment by XhmikosR** [comment]
@MayhemYDG: now that you see the warnings, the next step would be to fix the x64 ones, the `/EHsc` ones and the `NOMINMAX` redefine.

But wait so that we clean this up before merging.

**Comment by FeodorFitsner** [comment]
Put it to a separate .cmd file. Otherwise it's being run line by line.

**Comment by XhmikosR** [comment]
Yes I know but it should work with >-. I don't want to move it to a
separate file. :/

**Comment by FeodorFitsner** [comment]
>- allows defining multi-line string in yml, but unless it's marked as "ps:" AppVeyor breaks it to lines and run line by line

**Comment by XhmikosR** [comment]
That's too bad. Can't you make AppVeyor follow the specs?

**Comment by XhmikosR** [comment]
@MayhemYDG: so, just merge this and if AppVeyor follows the YAML specs, we can change the file.

**Comment by MayhemYDG** [comment]
Looks like appveyor only failed because of timeouts.
Do you know how to fix those warnings? Are they important? We should test x64 builds on all node versions.

**Comment by XhmikosR** [comment]
@MayhemYDG: it makes **no** sense to test on all x64 versions. Plus the build will take like 40 minutes to finish.

As for those errors, you should try increasing the timeout in your tests to something like 30000.

**Comment by MayhemYDG** [comment]
What about those warnings?
Would it make more sense to test all node versions on x64 and only test one of them on x86?

**Comment by XhmikosR** [comment]
Let me put it differently :)

Why don't you do that for Unix? It's the same thing, and I just chose the LTS version to test both.

What warnings are you referring to? Most seem to come from upstream brotli, but you could tweak the gyp switches for MSVC.

**Comment by MayhemYDG** [comment]
Good point. I'm not very familiar with the whole Windows server ecosystem, but I'd assume there is still a significant percentage of x86 users, while virtually everyone is on x64 on unix.

I'm referring to the warnings you mentioned in your second comment. The tests still work so if you think that's fine I'll happily merge this. `the /EHsc ones and the NOMINMAX redefine.`

**Comment by XhmikosR** [comment]
I'm looking into this as we speak and i'll ping you.

Testing the LTS version for both platforms seems fine to me.

**Comment by XhmikosR** [comment]
The timeout is fixed. Now testing the switches.

**Comment by XhmikosR** [comment]
I can't make the warnings go away even though I'm doing what I did in node-zopfli. Maybe @pierreinglebert has an idea.

Other than that, I'd say this is ready to merge after CI finishes.

**Comment by MayhemYDG** [comment]
Thanks!

**Pull request merged**
