### PR TITLE
Reduce buffering by using Nan::AsyncProgressQueueWorker

### PR DESCRIPTION
**Pull request by MayhemYDG**
@addaleax Yo, I'd appreciate a quick review.

Notably I tried using `Nan:: CopyBuffer` in `HandleProgressCallback`s. Surely node will count the copied buffer's size into account, so it doesn't need to be manually reported back to the gc?
If so, can `Allocator` be simplified?

### CODE REVIEW

**Comment by MayhemYDG** [comment]
I tried doing the `malloc`/`memcpy` part in `Execute()`, then do a `Nan::NewBuffer()` in `HandleProgressCallback()`, but it didn't work out. 😞

**Comment by MayhemYDG** [comment]
The biggest mystery left here is why do I have to manually do `delete this.encoder`/`delete this.decoder` in the JS side to force a call on the C++ destructor. It doesn't seem to be happening otherwise, and ends up leaking a massive amount of memory.

**Comment by MayhemYDG** [comment]
@kkoopa 
Would it make sense to add an optional parameter to `AsyncProgressQueueWorker`'s `progress.Send()` to prevent it from managing the buffer?
What I'd like to try is do the malloc/memcpy off the main thread, pass the buffer to `progress.Send()`, then let Node manage it by giving it to `Nan::NewBuffer()`.

**Comment by kkoopa** [comment]
I do not know. The included progress worker is meant for sending small progress messages during a long operation, not for streaming data without copying. It must do explicit synchronization to avoid race conditions.

If you use the normal AsyncWorker, it is easy to present a shared buffer after the callback is finished.

**Comment by MayhemYDG** [comment]
@kkoopa 
We do use AsyncWorker.
Here's the current workflow: we send from JS a buffer to de/compress, we let brotli process it off the main thread, we then get 0, 1, or more de/compressed chunks. We buffer those chunks until the current operation is complete, Once we're back on the main thread (`HandleOKCallback`) we send back an array of chunks (Node buffers) to the JS side.

In this PR I am experimenting with `AsyncProgressQueueWorker` in the hope to reduce latency/increase throughput by avoiding the step where we buffer the chunks, and instead send them back to JS-land asap.
Is `AsyncProgressQueueWorker` not the appropriate solution perhaps?

**Comment by kkoopa** [comment]
I do not think it is the right solution in itself. As I mentioned, this is not its intended use case. Most of the things included in NAN are reference implementations meant to cover common cases and show how things should be done.

I think a straight AsyncWorker on each chunk would be better, given large enough chunk size. The transition between C+++ and JavaScript is rather slow, so too frequent callbacks will lead to loss of performance.

Possibly you need to do some extra management before and after chunk processing to know when a full operation begins and ends, but that is a protocol matter.

**Pull request closed without merging**
