### PR TITLE
Upgrade brotli to v0.6.0 #32

### PR DESCRIPTION
**Pull request by MayhemYDG**
@addaleax could you review this please?
I mostly lazily copied the decoder implementation for this.
It seems to be compiling and working fine, except when I occasionally get a segmentation fault before the `should compress an empty buffer` test.

### CODE REVIEW

**Comment by addaleax** [comment]
Hi there! Sure, this looks good (at a somewhat quick glance). This patch seems enough to get everything working:

```diff
diff --git a/src/enc/stream_encode.cc b/src/enc/stream_encode.cc
index e8447fa7eb4e..6545a8bb83c8 100644
--- a/src/enc/stream_encode.cc
+++ b/src/enc/stream_encode.cc
@@ -91,6 +91,8 @@ NAN_METHOD(StreamEncode::Flush) {
   BrotliEncoderOperation op = info[0]->BooleanValue()
     ? BROTLI_OPERATION_FINISH
     : BROTLI_OPERATION_FLUSH;
+  obj->next_in = nullptr;
+  obj->available_in = 0;
   StreamEncodeWorker *worker = new StreamEncodeWorker(callback, obj, op);
   if (info[2]->BooleanValue()) {
     Nan::AsyncQueueWorker(worker);
```

<details><summary>Just in case if you’re wondering how I found this:</summary>

```
$ valgrind --track-origins=yes ~/src/node/master/node ./node_modules/.bin/_mocha -t 40000 test/brotliStream.js 
==15384== Memcheck, a memory error detector
==15384== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==15384== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==15384== Command: /home/xxxx/src/node/master/node ./node_modules/.bin/_mocha -t 40000 test/brotliStream.js
==15384== 
==15384== Warning: set address range perms: large range [0x28a3681eb000, 0x28a3881ec000) (noaccess)


  Brotli Stream
    compress
      ✓ should compress binary data (6927ms)
      ✓ should compress binary data (4292ms)
      ✓ should compress text data (871ms)
      ✓ should compress text data with quality=3 (104ms)
      ✓ should compress text data with quality=9 (867ms)
==15384== Thread 9:
==15384== Conditional jump or move depends on uninitialised value(s)
==15384==    at 0x9971C7A: BrotliEncoderCompressStream (encode.c:1725)
==15384==    by 0x998C3CB: StreamEncodeWorker::Execute() (stream_encode_worker.cc:20)
==15384==    by 0x998A463: Nan::AsyncExecute(uv_work_s*) (nan.h:1717)
==15384==    by 0x14718D3: worker (threadpool.c:95)
==15384==    by 0x5AF46C9: start_thread (pthread_create.c:333)
==15384==    by 0x5E130AE: clone (clone.S:105)
==15384==  Uninitialised value was created by a heap allocation
==15384==    at 0x4C2D1AF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15384==    by 0x9989782: StreamEncode::New(Nan::FunctionCallbackInfo<v8::Value> const&) (stream_encode.cc:64)
==15384==    by 0x9988653: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (nan_callbacks_12_inl.h:174)
==15384==    by 0x875988: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/xxxx/src/node/master/out/Release/node)
==15384==    by 0x8F9C9B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/xxxx/src/node/master/out/Release/node)
==15384==    by 0x8FB05B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/xxxx/src/node/master/out/Release/node)
==15384==    by 0x28A36838437C: ???
==15384==    by 0x28A3684376BC: ???
==15384==    by 0x28A368469E10: ???
==15384==    by 0x28A36843AFFB: ???
==15384==    by 0x28A36838579A: ???
==15384==    by 0x28A3684377BC: ???
```
</details>

**Comment by MayhemYDG** [comment]
Thank you.
Now I'm wondering why we don't need to do this on the decoder side of flushing.

**Comment by addaleax** [comment]
That might be pure luck :/ I’d just add the code there, to… for decoding, flushing and normal transforms should be (nearly) equivalent anyway.

**Comment by MayhemYDG** [comment]
Mmh, the encode flushing test randomly breaks on Travis, but not on AppVeyor. When it breaks the first buffer doesn't make it to the end of the test somehow. I can't think of why that it the case. Any ideas @addaleax?

**Comment by MayhemYDG** [comment]
Nevermind I seem to have fixed it: it was trying to flush while the encoding wasn't complete.

**Comment by addaleax** [comment]
Sorry for being a bit late, I was busy over the weekend. :) But yea, glad to hear you got everything working!

**Comment by MayhemYDG** [comment]
No problem!

**Pull request merged**
