### PR TITLE
Add conpression flushing #8

### PR DESCRIPTION
**Pull request by MayhemYDG**
Finally got around to work on this.

### CODE REVIEW

**Comment by MayhemYDG** [comment]
I get a segmentation if I chain two flush calls one after the other. 🤔
@addaleax might know more.

**Comment by addaleax** [comment]
So… one problem appears to be that `.flush()` calls are asynchronous, and when you call the method twice, two `Nan::AsyncQueueWorker()` calls are made, which can spawn workers on different threads. I don’t think there’s an easy way of making sure async workers are run sequentially (maybe there should be?), so maybe you’ll need to start synchronising stuff with mutexes. :/

Not sure whether that’s everything or not, though… setting `UV_THREADPOOL_SIZE=1` didn’t seem to help… :confused: 

And a small aside: I was at NodeConf Barcelona last week and it was awesome to see this module was mentioned in the HTTP compression talk! :tada:

**Comment by MayhemYDG** [comment]
While flushing is happening, we need to block both concurrent flushing, and encoding.
What I'm thinking is maybe set a flushing flag to true and call `this.write()`. Since `_transform` calls happen one at a time thanks to the callback function, it should work.

I also need to fix the `status.remaining` after flushing, and maybe check if there is anything to flush to begin with.

**Comment by MayhemYDG** [comment]
Actually I just used cork/uncork.

**Comment by addaleax** [comment]
> Actually I just used cork/uncork.

Oh, yeah, that’s the obvious approach I overlooked. :smile:

> Is there any video recording of that talk? This sounds big! :raised_hands:

I don’t think they are uploaded yet, but @lrlna has her slides up at https://lrlna.github.io/shiny-talks/nodeconf-bcn-2017/ (It’s just a small mention on slide 33, but still!)

**Comment by lrlna** [comment]
hehe yea, it's up there! I'll probably do a bit more of a mention when i give the talk at JSConf EU ✨

**Pull request merged**
